version: "3.6"

volumes:
    log:
        driver_opts:
            type: none
            device: <CURDIR>/vol/log
            o: bind
    rdmoapp:
        driver_opts:
            type: none
            device: <CURDIR>/vol/rdmo-app
            o: bind
    ve:
        driver_opts:
            type: none
            device: <CURDIR>/vol/ve
            o: bind

services:
    apache:
        build:
            context: ./apache
        container_name: rdc-apache
        ports:
            - "8484:80"
        volumes:
            - log:/vol/log
            - rdmoapp:/vol/rdmo-app
            - ve:/vol/ve
        env_file:
            - 'variables.env'
        depends_on:
            - rdmo

    postgres:
        build:
            context: ./postgres
        container_name: rdc-postgres
        env_file:
            - 'variables.env'

    rdmo:
        build:
            context: ./rdmo
        container_name: rdc-rdmo
        depends_on:
            - postgres
        volumes:
            - log:/vol/log
            - rdmoapp:/vol/rdmo-app
            - ve:/vol/ve
        env_file:
            - 'variables.env'
